### ISSUE TITLE
washinvestments data package review

### ISSUE THREAD

**Issue by margauxgo** [openwashdata/washinvestments#1]
Hi @mianzg could you please give me a first review of this data package?

**Comment by mianzg** [comment]
@margauxgo 
**README**
1. I personally prefer displaying code and its results together. The current version shows the plots first and a complete code script at the end. But this is a style choice, so I think it's up to what you think the best
2. The first figure stacks "Asia" and "Africa" together, I think a side-to-side bar plot could be more proper. 

**Package**
I tried with installing the package
1. The exported data is a data frame not a tibble. Is this on purpose?
2. The documentation doesn't show up when searching `?washinvestments`.Did you run `document()` and `check()`? I think the roxygen documentation inside `R/` is missing title and description too. 
3. I like the examples in the README, consider add or expand them in an example page when setting up pkgdown website.
